name: Docker Build CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'assets/doc_assets/**'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.MD'
      - '.github/*yml'
      - '.gitignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'assets/doc_assets/**'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.MD'
      - '.github/*yml'
      - '.gitignore'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPONAME }}:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
      # -
      #   name: Run Trivy vulnerability scanner for all CVEs (non-blocking)
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: ${{github.run_id}}
      #     format: 'table'
      #     exit-code: '0'
      #     ignore-unfixed: true
