[theme]
backgroundColor = "#202040"
secondaryBackgroundColor = "#543864"
primaryColor="#FF6363"
textColor = "#fafafa"
font="sans serif"

[server]
maxUploadSize = 100

[browser]
gatherUsageStats = false